# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: 
    steps:
    - uses: 

    - name: 
      uses: 
      with:
        go-version: '1.20'

    - name: 
      run: 

    - name: 
      run: 
